version: '3.1'

services:
  node:
    image: node:10.17.0
    volumes:
      - .:/code:rw
    command: bash /code/run.sh
    #command: bash -c "bash /code/run.sh > /code/run.log 2>&1"
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports: 
      - "4444:4444"
    logging:
      driver: none
 